export const APP_STATE = 'APP_STATE';
export const INCREASE_APPLE_NUMBER = 'INCREASE_APPLE_NUMBER';
export const DECREASE_APPLE_NUMBER = 'DECREASE_APPLE_NUMBER';

export const INCREASE_PEAR_NUMBER = 'INCREASE_PEAR_NUMBER';
export const DECREASE_PEAR_NUMBER = 'DECREASE_PEAR_NUMBER';
